name: CI
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./
      - name: Use Node.jstest
        uses: actions/setup-node@v1
      - name: NPM test
        run: npm -v
