name: CI
on: [push]

jobs:
  hello_world_job:
    uses: docker://openwebspace/cordova:8.1.2
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: openwebspace/cordova:8.1.2
