name: CI
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout Directory
      id: checkout
      uses: actions/checkout@v1
    - name: Get Docker Image
      id: docker
      uses: docker://openwebspace/cordova:8.1.2
      with:
        run:  cordova -v
