name: CI
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: touch sample.txt
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: sample.txt
          
