name: CI
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./
      - name: list directory
        run: cd MyApp/platforms/android/app/build
      - name: test files
        run: ls
